version: '2'

volumes: 
  build:
    driver: local
  cache:
    external: true 

services:

  test:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - cache:/cache
      - build:/build
    links:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      TEST_OUTPUT_DIR: /reports

  agent:
    image: freemanzhang/ansible
    links:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]


  builder:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    volumes:
      - build:/build
    entrypoint: "entrypoint.sh"
    command: ["pip", "wheel", "--no-index", "-f /build", "."]

  db:
    image: mysql
    hostname: db
  #  ports:
  #    - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
